### ISSUE TITLE
Rails 6.0.0.rc1:  ActiveStorage::FileNotFoundError on model save

### ISSUE THREAD

**Issue by oiuzikov** [igorkasyanchuk/active_storage_validations#31] opened 2019-06-05 18:13 UTC
The following declaration throws `ActiveStorage::FileNotFoundError` in Rails 6.0.0.rc1 when I try to save a model:

```ruby
validates :image, attached: true, content_type: IMAGE_CONTENT_TYPE,
  dimension: { width: IMAGE_WIDTH, height: IMAGE_HEIGHT }
```

with the following cause:

`
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/oleksandri/Code/marketplace/storage/08/3z/083z1pphjimzuwty55kqvb7t1hhj 
`

Is it supported in Rails 6?

Thank you for your valuable work

**Comment by igorkasyanchuk** [comment] 2019-06-05 18:47
Don't know. Maybe, we don't have specs for different versions. Please post full stack trace to see where is error happens

**Comment by oiuzikov** [comment] 2019-06-05 19:17
Thank you for quick reply. Here is the trace you asked for.

I also did a quick research and seems like ActiveStorage doesn't save the attachment to the file system before the model is saved which in turn breaks the validation flow...

Extracted source (around line 19): 
```ruby
def create
  @design = Design.new design_params
  if @design.save # <= line 19
    redirect_to user_designs_path
  else
    render :new
```

Exception causes:
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/oleksandri/Code/marketplace/storage/8c/ul/8culuojs36e2ol6q5a49g87s48a1
```
Request:
```
{"utf8"=>"✓",
 "authenticity_token"=>"2YS2nziC4UPNLXqipa2VPy73Hr2RXaRcyI7CXyCBLqV/2Q9ZtYLTeYhFzP4ifhiySShLtIR2xvMzNfLY7/M/0A==",
 "design"=>
  {"name"=>"New Design 1",
   "image"=>
    #<ActionDispatch::Http::UploadedFile:0x00007f64643857f0
     @content_type="image/png",
     @headers="Content-Disposition: form-data; name=\"design[image]\"; filename=\"small.png\"\r\n" + "Content-Type: image/png\r\n",
     @original_filename="small.png",
     @tempfile=#<File:/tmp/RackMultipart20190605-31557-1gs32cd.png>>},
 "button"=>""}
```

Full trace:
```
activestorage (6.0.0.rc1) lib/active_storage/service/disk_service.rb:136:in `rescue in stream'
activestorage (6.0.0.rc1) lib/active_storage/service/disk_service.rb:129:in `stream'
activestorage (6.0.0.rc1) lib/active_storage/service/disk_service.rb:28:in `block in download'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `instrument'
activestorage (6.0.0.rc1) lib/active_storage/service.rb:126:in `instrument'
activestorage (6.0.0.rc1) lib/active_storage/service/disk_service.rb:27:in `download'
activestorage (6.0.0.rc1) lib/active_storage/downloader.rb:32:in `download'
activestorage (6.0.0.rc1) lib/active_storage/downloader.rb:13:in `block in open'
activestorage (6.0.0.rc1) lib/active_storage/downloader.rb:24:in `open_tempfile'
activestorage (6.0.0.rc1) lib/active_storage/downloader.rb:12:in `open'
activestorage (6.0.0.rc1) lib/active_storage/service.rb:86:in `open'
activestorage (6.0.0.rc1) app/models/active_storage/blob.rb:206:in `open'
activestorage (6.0.0.rc1) lib/active_storage/analyzer.rb:27:in `download_blob_to_tempfile'
activestorage (6.0.0.rc1) lib/active_storage/analyzer/image_analyzer.rb:32:in `read_image'
activestorage (6.0.0.rc1) lib/active_storage/analyzer/image_analyzer.rb:21:in `metadata'
activestorage (6.0.0.rc1) app/models/active_storage/blob/analyzable.rb:47:in `extract_metadata_via_analyzer'
activestorage (6.0.0.rc1) app/models/active_storage/blob/analyzable.rb:29:in `analyze'
activesupport (6.0.0.rc1) lib/active_support/core_ext/module/delegation.rb:292:in `public_send'
activesupport (6.0.0.rc1) lib/active_support/core_ext/module/delegation.rb:292:in `method_missing'
activesupport (6.0.0.rc1) lib/active_support/core_ext/module/delegation.rb:292:in `public_send'
activesupport (6.0.0.rc1) lib/active_support/core_ext/module/delegation.rb:292:in `method_missing'
active_storage_validations (0.7.1) lib/active_storage_validations/dimension_validator.rb:42:in `block in validate_each'
active_storage_validations (0.7.1) lib/active_storage_validations/dimension_validator.rb:40:in `each'
active_storage_validations (0.7.1) lib/active_storage_validations/dimension_validator.rb:40:in `validate_each'
activemodel (6.0.0.rc1) lib/active_model/validator.rb:152:in `block in validate'
activemodel (6.0.0.rc1) lib/active_model/validator.rb:149:in `each'
activemodel (6.0.0.rc1) lib/active_model/validator.rb:149:in `validate'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:606:in `catch'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:606:in `block in default_terminator'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:202:in `block in halting'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:514:in `block in invoke_before'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:514:in `each'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:514:in `invoke_before'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:134:in `run_callbacks'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:827:in `_run_validate_callbacks'
activemodel (6.0.0.rc1) lib/active_model/validations.rb:407:in `run_validations!'
activemodel (6.0.0.rc1) lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:135:in `run_callbacks'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:827:in `_run_validation_callbacks'
activemodel (6.0.0.rc1) lib/active_model/validations/callbacks.rb:118:in `run_validations!'
activemodel (6.0.0.rc1) lib/active_model/validations.rb:337:in `valid?'
activerecord (6.0.0.rc1) lib/active_record/validations.rb:67:in `valid?'
activerecord (6.0.0.rc1) lib/active_record/validations.rb:84:in `perform_validations'
activerecord (6.0.0.rc1) lib/active_record/validations.rb:46:in `save'
activerecord (6.0.0.rc1) lib/active_record/transactions.rb:315:in `block in save'
activerecord (6.0.0.rc1) lib/active_record/transactions.rb:373:in `block in with_transaction_returning_status'
activerecord (6.0.0.rc1) lib/active_record/connection_adapters/abstract/database_statements.rb:277:in `block in transaction'
activerecord (6.0.0.rc1) lib/active_record/connection_adapters/abstract/transaction.rb:272:in `block in within_new_transaction'
/home/oleksandri/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
activerecord (6.0.0.rc1) lib/active_record/connection_adapters/abstract/transaction.rb:270:in `within_new_transaction'
activerecord (6.0.0.rc1) lib/active_record/connection_adapters/abstract/database_statements.rb:277:in `transaction'
activerecord (6.0.0.rc1) lib/active_record/transactions.rb:212:in `transaction'
activerecord (6.0.0.rc1) lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
activerecord (6.0.0.rc1) lib/active_record/transactions.rb:315:in `save'
activerecord (6.0.0.rc1) lib/active_record/suppressor.rb:44:in `save'
app/controllers/user/designs_controller.rb:19:in `create'
actionpack (6.0.0.rc1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0.rc1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0.rc1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0.rc1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0.rc1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.0.rc1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0.rc1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0.rc1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0.rc1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0.rc1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0.rc1) lib/action_dispatch/routing/route_set.rb:837:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/cookies.rb:644:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
activerecord (6.0.0.rc1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/static.rb:126:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:57:in `block in call'
activesupport (6.0.0.rc1) lib/active_support/notifications.rb:182:in `instrument'
actionpack (6.0.0.rc1) lib/action_dispatch/middleware/stack.rb:56:in `call'
railties (6.0.0.rc1) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread' 
`

**Comment by igorkasyanchuk** [comment] 2019-06-05 19:47
But with Rails 5.2 all is OK?

I think the problem is that in Rails 5 there were no validations and all records were persisted.
In Rails 6 team fixed only persistence issue, but build-in validations were not added. So now this issue exists.

I suggest trying to fix this issue and submit PR, I just don't have enough time to handle all activities.

Adding author of dimensions validation for advise: @phlegx

**Comment by igorkasyanchuk** [comment] 2019-06-05 19:55
issue is reproducable if you change in gemspec

s.add_dependency 'rails', '6.0.0.rc1'
(plus maybe bundle update sqlite)

and run

bundle exec rake test

**Comment by phlegx** [comment] 2019-06-11 12:12
Here the line of method `analyze`: [active_storage/blob/analyzable.rb#L28](https://github.com/rails/rails/blob/v6.0.0.rc1/activestorage/app/models/active_storage/blob/analyzable.rb#L28)

**Comment by imi56** [comment] 2019-07-14 06:09
Just commenting for more clarity. I am also facing the exact same issue.  If I remove `dimension` validation it works. 
rails: (6.0.0.rc1)
mini_magick (4.9.4)
active_storage_validations (0.7.1)

**Comment by igorkasyanchuk** [comment] 2019-07-15 21:19
after some time for investigation, I found the following. In Rails 6 files are stored on disk after record was saved.

You can see it here (for reading it works with different class and without attachable):

ruby
```
          def #{name}
            @active_storage_attached_#{name} ||= ActiveStorage::Attached::One.new("#{name}", self)
          end

          def #{name}=(attachable)
            attachment_changes["#{name}"] =
              if attachable.nil?
                ActiveStorage::Attached::Changes::DeleteOne.new("#{name}", self)
              else
                ActiveStorage::Attached::Changes::CreateOne.new("#{name}", self, attachable)
              end
            binding.pry
          end
```

http://prntscr.com/ofgv13 (I see one useful method "attachment_changes") which returns a hash of files which should be saved.

Looks like to validate attached files it's needed to check this has, e.g. `attachment_changes[<field_name>]` instead of blob.

**Comment by igorkasyanchuk** [comment] 2019-07-15 21:34
OK, here is an initial code fix which works with Rails 6 rc1 ONLY (for Rails 5.2 use current stable version 0.7.1): https://github.com/igorkasyanchuk/active_storage_validations/pull/33

who can try and see if it works?

**Comment by igorkasyanchuk** [comment] 2019-07-15 22:13
check this branch: https://github.com/igorkasyanchuk/active_storage_validations/tree/rails.6.rc1.fix if it works on real project

**Comment by igorkasyanchuk** [comment] 2019-07-18 19:08
OK, try this for Rails 6: 

```
gem 'active_storage_validations', github: 'igorkasyanchuk/active_storage_validations', branch: 'rails.6.rc1.fix'
```

**Closed by igorkasyanchuk** 2019-07-18 19:08 UTC

**Comment by danderozier** [comment] 2019-07-25 18:51
Howdy. I'm using the rails.6.rc1.fix branch, and I'm encountering an issue when I try to validate both the content_type and dimension of an attachment. 

```ruby
# app/models/image.rb

class Image < ApplicationRecord
  CONTENT_TYPES = %w[image/png image/jpg image/jpeg image/gif]

  has_one_attached :source

  validates :source, attached: true, content_type: CONTENT_TYPES,
                                     dimension: { width: { max: 5000 },
                                                  height: { max: 5000 } }
end
```

In my tests, I'm verifying that an Image with a PDF attachment should not be valid:
```ruby
# spec/models/image_spec.rb

RSpec.describe Image, type: :model do
  ...
  describe 'validations' do
    context 'with invalid file type' do
      subject { Fabricate.build(:image, filename: 'test.pdf') }
      it { expect(subject).to_not be_valid }
    end
  end
end
```

But this results in a `StandardError: File has no dimension and no width and height in metadata`. 

It seems that the dimension validator checks presence of the `:width` and `:height` keys regardless of whether the attachment is an image: 

https://github.com/igorkasyanchuk/active_storage_validations/blob/e4f6122ca6ca24a6bd396d0bba235f5c21fd765e/lib/active_storage_validations/dimension_validator.rb#L48

Is this expected behavior? In this case, instead of throwing an error, I would expect the dimension validation to simply fail — either the attachment's dimensions meet the criteria or they don't.

**Comment by danderozier** [comment] 2019-07-25 19:08
Update: I have a quick fix going here: https://github.com/danderozier/active_storage_validations/commit/a5d81ca4369fb078858ed4f53d2fdc7d0294a2c6

Happy to submit a PR if you think this is the right approach.

**Comment by igorkasyanchuk** [comment] 2019-07-26 08:34
@danderozier please make a PR to this PR, if specs are OK I'll merge
if possible you can improve specs, since now they are very basic

**Comment by phlegx** [comment] 2019-07-26 12:03
@igorkasyanchuk @danderozier so, in the quick fix if there is no metadata on an image the validation fails instead of rise an error? For me @danderozier solution is good! Thx

**Comment by igorkasyanchuk** [comment] 2019-07-29 18:09
@danderozier could you please make a PR with this fix. Please also do similar to `ActiveStorageValidations` file, it has a similar check so it will be useful

**Comment by danderozier** [comment] 2019-07-29 18:37
@igorkasyanchuk I'd be happy to — though I'm not sure what you're looking for, re: `ActiveStorageViolations` file, could you be more specific?

**Comment by igorkasyanchuk** [comment] 2019-07-29 18:54
@danderozier  I'm speaking about this commit https://github.com/danderozier/active_storage_validations/commit/a5d81ca4369fb078858ed4f53d2fdc7d0294a2c6

please pull the latest changes from my branch and see new file : AspectRatioValidator this for dimention validations, it has similar code, so I think this change is needed there too?
